version: "3.5"

services:
  synthetic_data_generator:
    build: 
      context: ../generator
      dockerfile: ../development/DataGeneratorDockerfile
    container_name: synthetic_data_generator
    command: tail -f /dev/null # Run Forever
    volumes:
      - ../generator:/app/src/map/generator:rw
      - ../tests:/app/src/map/tests:rw
    networks:
      - datazone

networks:
  datazone:
